spring:
  application:
    name: unidy

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/unidy?serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: ${JWT_SECRET}
  expire:
    access: 86400000
    refresh: 604800000

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        web: DEBUG


